### ISSUE TITLE
Redirect breaks with Antd

### ISSUE THREAD

**Issue by arnaudjnn** [fwojciec/simple-i18n-example#12]
After following [your tutorial](https://medium.com/swlh/how-to-build-a-multilingual-website-in-next-js-2924eeb462bc) and the [official implementation ](https://github.com/zeit/next.js/tree/canary/examples/with-ant-design-less)of Antd, the redirect from the naked domain example.com to example.com/[lang] doesn't work anymore. 

## What I've tried
It works well if I comment components with Antd.

**Comment by fwojciec** [comment]
Sorry, I've no experience with Antd and I can't really offer any meaningful help without some kind of reproduction example.

**Comment by arnaudjnn** [comment]
> Sorry, I've no experience with Antd and I can't really offer any meaningful help without some kind of reproduction example.

You can try to comment Header and Footer components inside Layout and the redirect works

**Comment by fwojciec** [comment]
Try replacing

```typescript
router.replace("/[lang]", `/${getInitialLocale()}`);
```

with

```typescript
document.location.pathname = `/${getInitialLocale()}`;
```
in the `pages/index.ts` file.

**Comment by arnaudjnn** [comment]
Awesome! Thank you so much for this fix and for the whole tutorial, it saved me a week!

**Comment by fwojciec** [comment]
Happy to hear it worked!

**Comment by alexllao** [comment]
Hi! It blocks my browsers.

`import React from "react";
import Head from "next/head";
import { getInitialLocale } from "../translations/getInitialLocale";
import { useRouter } from "next/dist/client/router";

function Index() {
    const router = useRouter()

    React.useEffect(() => {
        router.replace("/[lang]", `/${getInitialLocale()}`);        
    });

    return (
        <>
            <Head>
                <meta name="robots" content="noindex, nofollow" />
            </Head>
        </>
    );
};

export default Index;`

**Comment by fwojciec** [comment]
Try something like this:

```javascript
import React from "react";
import Head from "next/head";
import { getInitialLocale } from "../translations/getInitialLocale";

function Index() {
React.useEffect(() => {
    document.location.pathname = `/${getInitialLocale()}`;        
});

return (
    <>
        <Head>
            <meta name="robots" content="noindex, nofollow" />
        </Head>
    </>
);
};
```

**Comment by alexllao** [comment]
Thnks!!! It works!! Thnks a lot.

**Comment by alexllao** [comment]
I have been testing. Would it be possible to access the locale in a NextJS Document? This is my simple Document extension.

`import Document, { Html, Head, Main, NextScript } from 'next/document';

class MyDocument extends Document {
    render() {           
        return (
            <Html lang="xx">
                <Head>
                    <meta name="description" content="" />
                    <meta name="keywords" content="" />
                    <link rel="dns-prefetch" href="https://fonts.googleapis.com" />
                </Head>

                <body>
                    <Main />
                    <NextScript />
                </body>

            </Html>
        )
    }
}

export default MyDocument;`

Thnks

**Comment by alexllao** [comment]
Wouldn't it be interesting to have the "withLocale" in the App? I've a custom App extension.

`import { PageTransition } from 'next-page-transitions';

class MyApp extends App {
    render() {
        const { Component, pageProps, router } = this.props;
        return (
            <>
                <PageTransition timeout={300} classNames="page-transition">
                    <Component {...pageProps} key={router.route} />
                </PageTransition>
            </>
        );
    }
}

export default withGA("UA-XXXXXXX-X", Router)(MyApp);`

**Comment by BiscuiTech** [comment]
> 
> 
> I have been testing. Would it be possible to access the locale in a NextJS Document? This is my simple Document extension.
> 
> `import Document, { Html, Head, Main, NextScript } from 'next/document';
> 
> class MyDocument extends Document {
> render() {
> return (
> 
> 
> 
> 
> 
> ```
>             <body>
>                 <Main />
>                 <NextScript />
>             </body>
> 
>         </Html>
>     )
> }
> ```
> 
> }
> 
> export default MyDocument;`
> 
> Thnks

_document.tsx access to locale (or lang in general) is a known issue, reference here: https://github.com/zeit/next.js/issues/9160
