### ISSUE TITLE
Images has wrong path in components

### ISSUE THREAD

**Issue by a-vershinin** [fwojciec/simple-i18n-example#15]
Hello!

I'm using you example with localization and found that images from component does not loading.

I created component **ArtistBackground** with tag **img** and **src** and added it as component to **Artist** component.

```
<div>
      <h1>René Magritte</h1>
      <ArtistBackground />
      <p>{t("bio")}</p>
      <a href={`http://${locale}.wikipedia.org/wiki/René_Magritte`}>
        {t("readMore")}
      </a>
</div>
```

When we are moving to page **/artist,** image don't load and tag **img**  is trying to load image from path http://localhost:3000/en/artist, but image is in folder **public/img/image** and we don't see image in component.
If I'm creating folders for path **public/en/img/image.jpg**, that it's works. This approach requires is copying images by each languages, it's not suitable. 
Hot to fix it?

**Comment by fwojciec** [comment]
Can you also post the code of ArtistBackground component?

**Comment by a-vershinin** [comment]
Sure

```
const ArtistBackground = () => {
  return (
    <div>
      <img src="./img/magritte.jpg" alt="Some text" />
    </div>
  );
};
```
