### ISSUE TITLE
Conflict when removing Typescript?

### ISSUE THREAD

**Issue by arzafran** [fwojciec/simple-i18n-example#3]
I've cloned the project and I'm trying to remove TS because I would like to use this approach on a NEXTjs (with JS only).
But I have the same issue here as I have with my project, it's as follows:

```
Can't import the named export 'feature' 
from non EcmaScript module (only default export is available)
ModuleDependencyError: 
Can't import the named export 'feature' from non EcmaScript module 
(only default export is available)
[...]
```

I've basically removed all the .tsx and TypeScript related settings.

**Comment by arzafran** [comment]
Well after trying different stuff, maybe there was something wrong with how I was compiling TypeScript.
after compiling removing noEmit and replacing `.tsx` files it magically worked.
Thanks for putting up the guide! really helpful :D

**Comment by arzafran** [comment]
Here's a fork with my code in case anyone is in the same situation:

https://github.com/arzafran/simple-i18n-example/tree/js-version

**Comment by fwojciec** [comment]
Thank you Franco!
