### ISSUE TITLE
no lang attribute on 'html' tag

### ISSUE THREAD

**Issue by n12o** [fwojciec/simple-i18n-example#7]
Hello. I've looked for examples of nextjs statically rendered websites that enable multiple languages and this example seems just what I need. I haven't fully tested or read your example but one thing I found is that 'html' tag doesn't have a 'lang' attribute. 

It seems that the only way available to change 'html' attribute is by creating '_document.js' file in the 'pages' folder. However it doesn't seem possible to make it dynamic for statically rendered pages. 

Is there any way out of this situation?

**Comment by BiscuiTech** [comment]
Hey, you can follow [this issue](https://github.com/zeit/next.js/issues/9160) on the next.js repo.

EDIT: If you want to code your own, [this user has figured it out](https://github.com/zeit/next.js/issues/9160#issuecomment-545001656). It's also easy to tack it on with the _localization api_ version of this repo.
